name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier check
        run: npx prettier --check .

      # If you add TypeScript later, you can uncomment this:
      # - name: Type-check
      #   run: npx tsc --noEmit

